import { actionType, buildAction } from '../config'

export const getProductAction = actionType('GET_PRODUCT')
export const listProductByCategoryAction = actionType('LIST_PRODUCTBYCATEGORY')
export const listProductBySearchAction = actionType('LIST_PRODUCTBYSEARCH')
export const addToWishlistAction = actionType('ADD_TO_WISHLIST')
export const addToWishlistHomeAction = actionType('ADD_TOWISHLIST_HOME')
export const getDiscussionAction = actionType('GET_DISCUSSION')
export const newDiscussionAction = actionType('NEW_DISCUSSION')
export const getCommentAction = actionType('GET_COMMENT')
export const newCommentAction = actionType('NEW_COMMENT')
export const reportProductAction = actionType('REPORT_PRODUCT')

export const getProduct = params => buildAction(getProductAction.request, params)
export const listProductByCategory = params => buildAction(listProductByCategoryAction.request, params)
export const listProductBySearch = params => buildAction(listProductBySearchAction.request, params)
export const addToWishlist = params => buildAction(addToWishlistAction.request, params)
export const addToWishlistHome = params => buildAction(addToWishlistHomeAction.request, params)
export const getDiscussion = params => buildAction(getDiscussionAction.request, params)
export const newDiscussion = params => buildAction(newDiscussionAction.request, params)
export const getComment = params => buildAction(getCommentAction.request, params)
export const newComment = params => buildAction(newCommentAction.request, params)
export const reportProduct = params => buildAction(reportProductAction.request, params)
