import { actionType, buildAction } from '../config'

export const loginAction = actionType('USER_LOGIN')
export const verificationAction = actionType('USER_VERIFICATION')
export const loginSocialAction = actionType('LOGIN_SOCIAL')
export const logoutAction = actionType('USER_LOGOUT')
export const registerAction = actionType('USER_REGISTER')
export const newPasswordAction = actionType('NEW_PASSWORD')
export const changePasswordAction = actionType('CHANGE_PASSWORD')
export const forgetPasswordAction = actionType('FORGET_PASSWORD')
export const getProfileAction = actionType('GET_PROFILE')
export const getProfileManageAction = actionType('GET_PROFILE_MANAGE')
export const updateProfileAction = actionType('UPDATE_PROFILE')
export const validateTokenAction = actionType('VALIDATE_TOKEN')
export const getBalanceAction = actionType('USER_BALANCE')
export const favoriteStoreAction = actionType('FAVORITE_STORE')
export const countBucketAction = actionType('COUNT_BUCKET')
export const getBucketAction = actionType('GET_BUCKET')
export const addToBucketAction = actionType('ADD_TO_BUCKET')
export const getPhoneAction = actionType('GET_PHONE')
export const updatePhoneAction = actionType('UPDATE_PHONE')
export const getDiscussionAction = actionType('GET_DISCUSSION')
export const listFavoriteAction = actionType('LIST_FAVORITE_STORE')
export const sendOTPPhoneAction = actionType('SEND_OTP_PHONE')
export const verifyPhoneAction = actionType('VERIFY_PHONE')
export const IS_LOGIN = 'IS_LOGIN'

export const login = params => buildAction(loginAction.request, params)
export const verification = params => buildAction(verificationAction.request, params)
export const loginSocial = params => buildAction(loginSocialAction.request, params)
export const logout = buildAction(logoutAction.request)
export const register = params => buildAction(registerAction.request, params)
export const newPassword = params => buildAction(newPasswordAction.request, params)
export const changePassword = params => buildAction(changePasswordAction.request, params)
export const forgetPassword = params => buildAction(forgetPasswordAction.request, params)
export const getProfile = params => buildAction(getProfileAction.request, params)
export const getProfileManage = params => buildAction(getProfileManageAction.request, params)
export const updateProfile = params => buildAction(updatePhoneAction.request, params)
export const validateToken = params => buildAction(validateTokenAction.request, params)
export const getBalance = buildAction(getBalanceAction.request)
export const favoriteStore = params => buildAction(favoriteStoreAction.request, params)
export const countBucket = buildAction(countBucketAction.request)
export const getBucket = buildAction(getBucketAction.request)
export const addToBucket = params => buildAction(addToBucketAction.request, params)
export const getPhone = buildAction(getPhoneAction.request)
export const updatePhone = params => buildAction(updatePhoneAction.request, params)
export const getDiscussion = params => buildAction(getDiscussionAction.request, params)
export const listFavorite = params => buildAction(listFavoriteAction.request, params)
export const sendOTPPhone = params => buildAction(sendOTPPhoneAction.request, params)
export const verifyPhone = params => buildAction(verifyPhoneAction.request, params)
export const stateLogin = buildAction(IS_LOGIN)
